### ISSUE TITLE
After save the calendar disappears

### ISSUE THREAD

**Issue by dmateosj** [uwctri/CalendarQuestions#10]
I cant get it  working after save, the calendar dissapears. But it worked before, I dont know what happened

**Comment by aanunez** [comment]
Could you provide any additional information? Error text, screenshots of the issue, redcap version, EM version etc.

**Comment by aanunez** [comment]
Are you certain that you don't have branching logic that is hiding the calendar field when it is not blank? Could you check for any javascript errors in the developer console (press Ctrl+Shift+I).

**Comment by aanunez** [comment]
I see the issue, you have maxed out the amount of data we can store in the calendar. If you open the settings for the module you can see the top 5 records that use a large amount of their available storage space. There is currently no method to allow for more data. You will need to either create an additional calendar start saving data to there or do a data correction that I've outline below (complex).

Data correction:
Its important to understand that you could corrupt calendar data if you aren't confident when performing these actions. Only do this if you are ok with manipulating the json created by the calendar. 

The calendar stores data as a json string into a text field. Redcap limits text to 64kb so that is the most data we can store. All variables created for the calendar have names that are used in the json, so you can limit the amount of space used by limiting the variable's name length. To edit these names follow these steps:
* Do a data export of the current calendar metadata. Make a copy so you have one to edit and one as a backup.
* Update all of the names to something very short in the EM config
* In Excel (or similar) edit all the field names to the new names.
* Load the data back into redcap
* Verify that the calendar still works as expected with all data.

After doing this you can see how much space you have saved by check the EM config, it will list the top 5 records with the most calendar data.

**Comment by aanunez** [comment]
Marking this as both a bug and and enhancement. We need to at least make the user aware that the calendar is full and can't save any additional data.

**Comment by aanunez** [comment]
Resolved in most recent release by allowing compression and warning the user when a field is close to being full.
